### ISSUE TITLE
gcr.io 代理有问题

### ISSUE THREAD

**Issue by yangchuansheng** [lework/cloudflare-workers#1]
gcr.io 代理只能用 docker 拉取，使用 podman、crictl 和 skopeo 都无法拉取，报错如下：

![](https://cdn.jsdelivr.net/gh/yangchuansheng/imghosting/img/20200819220459.png)

**Comment by lework** [comment]
这个是  `$custom_domian` 这个变量未定义导致的，现已修复完成，请拉取最新代码

https://github.com/lework/cloudflare-workers/blob/master/gcr_proxy.js
