### ISSUE TITLE
拉取镜像时出现ipv6网络不可达的错误

### ISSUE THREAD

**Issue by chenyaofo** [lework/cloudflare-workers#2]
非常感谢您提供的脚本可以将cloudflare worker作为dockerhub的镜像，但是我在使用过程中遇到了一些问题，想问问您是否知道解决办法。

通过您部署的worker拉取镜像时，出现如下错误：
```
% docker pull docker.lework.workers.dev/library/ubuntu:20.04
Error response from daemon: Head "https://docker.lework.workers.dev/v2/library/ubuntu/manifests/20.04": Get "https://auth.ipv6.docker.com/token?scope=repository%3Alibrary%2Fubuntu%3Apull&service=registry.docker.io": dial tcp [2600:1f18:2148:bc01:6c07:dc0:c4d8:ebcc]:443: connect: network is unreachable
```
看报错的意思是拉取是还需要访问`auth.ipv6.docker.com`这个地址，但是由于我的机器不支持ipv6，所以这个地址不可达，然后就报错了。我在另外一台支持ipv6的机器上运行同样的命令是可以正常拉取的。我个人分析是因为cloudflare的worker是支持ipv6的，所以选择了`auth.ipv6.docker.com`的这个地址；但是我不是很明白为什么我的机器还需要访问`auth.ipv6.docker.com`，按道理所有的请求都是由cloudflare的worker代理了才对啊。

**Comment by chenyaofo** [comment]
补充：只有从dockerhub的worker代理拉取会出现这个情况，从quay和gcr的worker代理拉取不会出现。

**Comment by bestruirui** [comment]
我也遇到了这个问题
