### ISSUE TITLE
可否更新下gcr那个js文件

### ISSUE THREAD

**Issue by nixilin** [lework/cloudflare-workers#3]
如标题
效仿文档，手动执行 docker pull gcr.lework.workers.dev/kaniko-project/executor 没问题，但按照gcr_proxy.js里的内容部署到自己的cf worker再去执行docker pull就各种报错。workers_url 变量的值对应调整过。
不知道是不是当前 gcr.lework.workers.dev 这个worker用的脚本已更新了，而github这边没更新？
谢谢～

**Comment by lework** [comment]
脚本和代码仓库的一致。
